# SonarQube project configuration
sonar.projectKey=php-sf-template
sonar.projectName=PHP Symfony Template
sonar.projectVersion=1.0.0

# Source paths
sonar.sources=src
sonar.tests=tests

# Language
sonar.language=php

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage reports
sonar.php.coverage.reportPaths=var/coverage/clover.xml
sonar.php.tests.reportPath=var/coverage/junit.xml

# Exclusions
sonar.exclusions=\
    var/**,\
    vendor/**,\
    public/**,\
    config/**,\
    src/Infrastructure/DataFixtures/**,\
    node_modules/**

sonar.test.exclusions=\
    vendor/**

# Code coverage exclusions
sonar.coverage.exclusions=\
    tests/**,\
    features/**,\
    config/**,\
    public/**,\
    src/Infrastructure/DataFixtures/**

# Duplications exclusions
sonar.cpd.exclusions=\
    tests/**,\
    features/**

# Quality Gate
sonar.qualitygate.wait=true
